export const ADD_FINANCED_ITEM = 'ADD_FINANCED_ITEM';
export const UPDATE_CUSTOMER_DETAILS = 'UPDATE_CUSTOMER_DETAILS';
export const UPDATE_FINANCED_ITEM = 'UPDATE_FINANCED_ITEM';
export const UPDATE_FINANCED_ITEMS = 'UPDATE_FINANCED_ITEMS';